### ISSUE TITLE
telemetry on a taranis X9D

### ISSUE THREAD

**Issue by Pascal-m** [silver13/H8mini_blue_board#8]
Hello is it possible to have telemetry on a taranis X9D + with the blue version of the card?

**Comment by silver13** [comment]
Should be, telemetry is included on all boards H8 boards now by default

**Comment by Pascal-m** [comment]
ok think you :-)
I try to setup  on my taranis and I receive nothing :-(
I join my _config.h of my multiprotocol card.
[_Config.h.txt](https://github.com/silver13/H8mini_blue_board/files/751785/_Config.h.txt)
Thk

**Comment by silver13** [comment]
I don't have a taranis, so I can't help you much more, the line looks ok to me.

`/*	14	*/	{MODE_BAYANG,	BAYANG		,	0	,	P_HIGH	,	NO_AUTOBIND	,	1		},`

Perhaps the problem is between the module and tx, or in tx settings

You could always ask in either the h8 thread or the module thread, but the taranis is less used with the h8, only a couple of people posted about telemetry use

**Comment by Pascal-m** [comment]
ok thank you :)
I open a new thread on rcgroup [here](https://www.rcgroups.com/forums/showthread.php?2827099-H8-Mini-Taranis-X9D-Telemetry)
Thk

**Comment by silver13** [comment]
good luck
